package ru.justlearn.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF715188)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF2DAFF)
val onPrimaryContainerLight = Color(0xFF2A0C40)
val secondaryLight = Color(0xFF675A6E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEEDDF5)
val onSecondaryContainerLight = Color(0xFF221829)
val tertiaryLight = Color(0xFF815155)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDADB)
val onTertiaryContainerLight = Color(0xFF321015)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FD)
val onBackgroundLight = Color(0xFF1E1A20)
val surfaceLight = Color(0xFFFFF7FD)
val onSurfaceLight = Color(0xFF1E1A20)
val surfaceVariantLight = Color(0xFFEADFEA)
val onSurfaceVariantLight = Color(0xFF4B454D)
val outlineLight = Color(0xFF7C757E)
val outlineVariantLight = Color(0xFFCDC3CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF332F35)
val inverseOnSurfaceLight = Color(0xFFF7EEF6)
val inversePrimaryLight = Color(0xFFDEB8F7)

val primaryDark = Color(0xFFDEB8F7)
val onPrimaryDark = Color(0xFF402357)
val primaryContainerDark = Color(0xFF583A6F)
val onPrimaryContainerDark = Color(0xFFF2DAFF)
val secondaryDark = Color(0xFFD2C1D9)
val onSecondaryDark = Color(0xFF372C3F)
val secondaryContainerDark = Color(0xFF4E4256)
val onSecondaryContainerDark = Color(0xFFEEDDF5)
val tertiaryDark = Color(0xFFF4B7BB)
val onTertiaryDark = Color(0xFF4C2529)
val tertiaryContainerDark = Color(0xFF663B3E)
val onTertiaryContainerDark = Color(0xFFFFDADB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFE8E0E8)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFE8E0E8)
val surfaceVariantDark = Color(0xFF4B454D)
val onSurfaceVariantDark = Color(0xFFCDC3CE)
val outlineDark = Color(0xFF968E98)
val outlineVariantDark = Color(0xFF4B454D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E0E8)
val inverseOnSurfaceDark = Color(0xFF332F35)
val inversePrimaryDark = Color(0xFF715188)







